# Generated by Django 5.2 on 2025-05-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeProperty',
        ),
    ]
