
const List<String> paletteList = [
  'savory',
  'spicy',
  'sweet',
  'sour',
  'herby',
  'umami',
  'earthy',
  'fruity',
  'smoky',
  'neutral',
  'bitter',
];



const List<String> availableIngredients = [
      'olive oil',
      'canola oil',
      'all purpose flour',
      'sugar',
      'salt',
      'black pepper',
      'garlic',
      'onion',
      'butter',
      'eggs',
      'milk',
      'water',
      'chicken broth',
      'vegetable oil',
      'baking powder',
      'baking soda',
      'vanilla extract',
      'lemon juice',
      'soy sauce',
      'rice',
      'pasta',
      'tomato',
      'tomato sauce',
      'tomato paste',
      'cheese',
      'cheddar cheese',
      'parmesan cheese',
      'mozzarella cheese',
      'heavy cream',
      'sour cream',
      'yogurt',
      'mayonnaise',
      'honey',
      'brown sugar',
      'powdered sugar',
      'cornstarch',
      'vinegar',
      'apple cider vinegar',
      'balsamic vinegar',
      'red wine vinegar',
      'white wine vinegar',
      'mustard',
      'dijon mustard',
      'yellow mustard',
      'ketchup',
      'worcestershire sauce',
      'hot sauce',
      'sriracha',
      'bay leaf',
      'oregano',
      'basil',
      'thyme',
      'rosemary',
      'parsley',
      'cilantro',
      'cumin',
      'coriander',
      'paprika',
      'smoked paprika',
      'cayenne pepper',
      'red pepper flakes',
      'chili powder',
      'curry powder',
      'turmeric',
      'ginger',
      'nutmeg',
      'cinnamon',
      'cloves',
      'allspice',
      'cardamom',
      'star anise',
      'fennel seed',
      'sesame seeds',
      'poppy seeds',
      'caraway seeds',
      'celery seed',
      'mustard seeds',
      'bread crumbs',
      'panko breadcrumbs',
      'oats',
      'cornmeal',
      'flour tortillas',
      'corn tortillas',
      'potatoes',
      'sweet potatoes',
      'carrots',
      'celery',
      'bell peppers',
      'green bell peppers',
      'red bell peppers',
      'yellow bell peppers',
      'jalapeño peppers',
      'serrano peppers',
      'habanero peppers',
      'cucumber',
      'zucchini',
      'yellow squash',
      'eggplant',
      'mushrooms',
      /* 'white mushrooms',
      'cremini mushrooms',
      'portobello mushrooms',
      'shiitake mushrooms',
      'spinach',
      'kale',
      'lettuce',
      'romaine lettuce',
      'iceberg lettuce',
      'arugula',
      'swiss chard',
      'collard greens',
      'cabbage',
      'green cabbage',
      'red cabbage',
      'bok choy',
      'brussels sprouts',
      'cauliflower',
      'broccoli',
      'asparagus',
      'green beans',
      'peas',
      'corn',
      'avocado',
      'lime',
      'lemon',
      'orange',
      'apple',
      'banana',
      'strawberries',
      'blueberries',
      'raspberries',
      'blackberries',
      'peaches',
      'pears',
      'plums',
      'cherries',
      'grapes',
      'pineapple',
      'mango',
      'kiwi',
      'coconut',
      'raisins',
      'dates',
      'prunes',
      'apricots',
      'figs',
      'almonds',
      'walnuts',
      'pecans',
      'cashews',
      'peanuts',
      'hazelnuts',
      'pistachios',
      'sunflower seeds',
      'pumpkin seeds',
      'chia seeds',
      'flax seeds',
      'quinoa',
      'couscous',
      'bulgur',
      'barley',
      'lentils',
      'black beans',
      'kidney beans',
      'pinto beans',
      'navy beans',
      'garbanzo beans',
      'cannellini beans',
      'split peas',
      'black eyed peas',
      'tofu',
      'tempeh',
      'seitan',
      'chicken',
      'chicken breast',
      'chicken thighs',
      'chicken wings',
      'chicken drumsticks',
      'turkey',
      'ground turkey',
      'turkey breast',
      'beef',
      'ground beef',
      'steak',
      'ribeye steak',
      'sirloin steak',
      'flank steak',
      'short ribs',
      'beef chuck',
      'pork',
      'pork chops',
      'pork tenderloin',
      'pork shoulder',
      'bacon',
      'ham',
      'sausage',
      'italian sausage',
      'chorizo',
      'hot dogs',
      'lamb',
      'lamb chops',
      'ground lamb',
      'fish',
      'salmon',
      'tuna',
      'cod',
      'halibut',
      'tilapia',
      'trout',
      'shrimp',
      'prawns',
      'scallops',
      'lobster',
      'crab',
      'clams',
      'mussels',
      'oysters',
      'anchovies',
      'sardines',
      'bread',
      'white bread',
      'whole wheat bread',
      'baguette',
      'ciabatta',
      'sourdough bread',
      'pita bread',
      'naan',
      'tortilla chips',
      'potato chips',
      'pretzels',
      'crackers',
      'saltine crackers',
      'graham crackers',
      'chocolate',
      'dark chocolate',
      'milk chocolate',
      'white chocolate',
      'chocolate chips',
      'cocoa powder',
      'vanilla bean',
      'maple syrup',
      'molasses',
      'agave nectar',
      'corn syrup',
      'peanut butter',
      'almond butter',
      'jam',
      'jelly',
      'marmalade',
      'hummus',
      'tahini',
      'soy milk',
      'almond milk',
      'coconut milk',
      'rice milk',
      'oat milk',
      'whipping cream',
      'half and half',
      'buttermilk',
      'evaporated milk',
      'condensed milk',
      'cream cheese',
      'ricotta cheese',
      'feta cheese',
      'goat cheese',
      'blue cheese',
      'gorgonzola cheese',
      'provolone cheese',
      'swiss cheese',
      'monterey jack cheese',
      'pepper jack cheese',
      'colby cheese',
      'american cheese',
      'velveeta cheese',
      'wine',
      'red wine',
      'white wine',
      'sherry',
      'beer',
      'rum',
      'vodka',
      'gin',
      'tequila',
      'whiskey',
      'bourbon',
      'scotch',
      'cognac',
      'brandy',
      'coffee',
      'tea',
      'green tea',
      'black tea',
      'herbal tea',
      'sparkling water',
      'club soda',
      'tonic water',
      'lemonade',
      'orange juice',
      'apple juice',
      'cranberry juice',
      'grapefruit juice',
      'pineapple juice',
      'tomato juice',
      'vegetable juice',
      'soda',
      'cola',
      'ginger ale',
      'root beer',
      'lemon lime soda',
      'gelatin',
      'yeast',
      'active dry yeast',
      'instant yeast',
      'shortening',
      'lard',
      'bacon fat',
      'duck fat',
      'chicken fat',
      'beef fat',
      'vegetable shortening',
      'margarine',
      'vegetable spread',
      'cooking spray',
      'nonstick spray',
      'ice',
      'dry ice',
      'liquid smoke',
      'food coloring',
      'vanilla pudding',
      'chocolate pudding',
      'butterscotch pudding',
      'tapioca pudding',
      'custard',
      'flan',
      'ice cream',
      'vanilla ice cream',
      'chocolate ice cream',
      'strawberry ice cream',
      'sherbet',
      'sorbet',
      'whipped topping',
      'cool whip',
      'marshmallows',
      'sprinkles',
      'candy',
      'caramels',
      'toffee',
      'gumdrops',
      'licorice',
      'gummy bears',
      'jelly beans',
      'mints',
      'peppermint',
      'cinnamon candy',
      'popcorn',
      'caramel corn',
      'cheese popcorn',
      'peanut brittle',
      'trail mix',
      'granola',
      'protein powder',
      'whey protein',
      'soy protein',
      'nutritional yeast',
      'wheat germ',
      'bran',
      'wheat bran',
      'oat bran',
      'psyllium husk',
      'arrowroot powder',
      'tapioca flour',
      'almond flour',
      'coconut flour',
      'rice flour',
      'chickpea flour',
      'buckwheat flour',
      'corn flour',
      'potato flour',
      'semolina',
      'bread flour',
      'cake flour',
      'pastry flour',
      'self rising flour',
      'whole wheat flour',
      'gluten free flour',
      'pancake mix',
      'biscuit mix',
      'cornbread mix',
      'cake mix',
      'brownie mix',
      'cookie mix',
      'muffin mix',
      'pie crust',
      'phyllo dough',
      'puff pastry',
      'pizza dough',
      'bread dough',
      'cookie dough',
      'brownie batter',
      'cake batter',
      'pancake batter',
      'waffle batter',
      'crepe batter',
      'french toast batter',
      'tempura batter',
      'beer batter',
      'marinade',
      'rub',
      'dry rub',
      'seasoning salt',
      'garlic salt',
      'onion salt',
      'celery salt',
      'seasoning blend',
      'italian seasoning',
      'poultry seasoning',
      'pumpkin pie spice',
      'apple pie spice',
      'chai spice',
      'five spice powder',
      'adobo seasoning',
      'creole seasoning',
      'cajun seasoning',
      'blackening seasoning',
      'jerk seasoning',
      'taco seasoning',
      'fajita seasoning',
      'ranch seasoning',
      'sazon seasoning',
      'old bay seasoning',
      'everything bagel seasoning',
      'furikake',
      'zaatar',
      'sumac',
      'harissa',
      'sambal oelek',
      'gochujang',
      'miso paste',
      'hoisin sauce',
      'oyster sauce',
      'fish sauce',
      'teriyaki sauce',
      'ponzu sauce',
      'duck sauce',
      'plum sauce',
      'sweet chili sauce',
      'peanut sauce',
      'alfredo sauce',
      'marinara sauce',
      'pesto',
      'tzatziki sauce',
      'aioli',
      'remoulade sauce',
      'tartar sauce',
      'cocktail sauce',
      'bbq sauce',
      'honey mustard',
      'ranch dressing',
      'blue cheese dressing',
      'caesar dressing',
      'italian dressing',
      'french dressing',
      'thousand island dressing',
      'vinaigrette',
      'balsamic vinaigrette',
      'raspberry vinaigrette',
      'honey vinaigrette',
      'mustard vinaigrette',
      'citrus vinaigrette',
      'herb vinaigrette',
      'shallot vinaigrette',
      'garlic vinaigrette',
      'ginger vinaigrette',
      'sesame vinaigrette',
      'soy vinaigrette',
      'wasabi',
      'horseradish',
      'ginger paste',
      'garlic paste',
      'tomato puree',
      'apple puree',
      'banana puree',
      'pumpkin puree',
      'sweet potato puree',
      'butternut squash puree',
      'cauliflower puree',
      'avocado puree',
      'mango puree',
      'pear puree',
      'peach puree',
      'berry puree',
      'fruit puree',
      'vegetable puree',
      'bean puree',
      'lentil puree',
      'hummus',
      'guacamole',
      'salsa',
      'pico de gallo',
      'salsa verde',
      'corn salsa',
      'mango salsa',
      'pineapple salsa',
      'peach salsa',
      'black bean salsa',
      'tomato salsa',
      'fruit salsa',
      'chutney',
      'mango chutney',
      'apple chutney',
      'tomato chutney',
      'onion chutney',
      'cranberry chutney',
      'pear chutney',
      'peach chutney',
      'plum chutney',
      'fig chutney',
      'relish',
      'pickle relish',
      'corn relish',
      'pepper relish',
      'onion relish',
      'cucumber relish',
      'zucchini relish',
      'eggplant relish',
      'tomato relish',
      'fruit relish',
      'vegetable relish',
      'pickles',
      'dill pickles',
      'bread and butter pickles',
      'sweet pickles',
      'gherkins',
      'cornichons',
      'pickled jalapeños',
      'pickled onions',
      'pickled beets',
      'pickled carrots',
      'pickled cucumbers',
      'pickled ginger',
      'pickled vegetables',
      'kimchi',
      'sauerkraut',
      'olives',
      'black olives',
      'green olives',
      'kalamata olives',
      'olive tapenade',
      'capers',
      'artichoke hearts',
      'sun dried tomatoes',
      'roasted red peppers',
      'pepperoncini',
      'giardiniera',
      'banana peppers',
      'cherry peppers',
      'pepperoni',
      'salami',
      'prosciutto',
      'pancetta',
      'capicola',
      'soppressata',
      'mortadella',
      'corned beef',
      'pastrami',
      'roast beef',
      'turkey breast',
      'chicken breast',
      'ham',
      'bologna',
      'liverwurst',
      'braunschweiger',
      'head cheese',
      'blood sausage',
      'andouille sausage',
      'kielbasa',
      'bratwurst',
      'italian sausage',
      'breakfast sausage',
      'chorizo',
      'linguica',
      'loukaniko',
      'merguez',
      'sucuk',
      'noodles',
      'ramen noodles',
      'udon noodles',
      'soba noodles',
      'rice noodles',
      'vermicelli',
      'angel hair pasta',
      'spaghetti',
      'linguine',
      'fettuccine',
      'penne',
      'rigatoni',
      'ziti',
      'macaroni',
      'fusilli',
      'rotini',
      'farfalle',
      'orzo',
      'lasagna noodles',
      'manicotti',
      'cannelloni',
      'ravioli',
      'tortellini',
      'gnocchi',
      'pierogi',
      'dumplings',
      'wonton wrappers',
      'egg roll wrappers',
      'spring roll wrappers',
      'phyllo dough',
      'puff pastry',
      'pie crust',
      'tart shell',
      'graham cracker crust',
      'cookie crust',
      'shortbread crust',
      'pastry dough',
      'biscuit dough',
      'pizza dough',
      'bread dough',
      'roll dough',
      'croissant dough',
      'danish dough',
      'brioche dough',
      'challah dough',
      'bagel dough',
      'pretzel dough',
      'doughnut dough',
      'fritter batter',
      'pancake batter',
      'waffle batter',
      'crepe batter',
      'french toast batter',
      'tempura batter',
      'beer batter',
      'cake batter',
      'brownie batter',
      'cookie dough',
      'muffin batter',
      'quick bread batter',
      'yeast bread dough',
      'sourdough starter',
      'poolish',
      'biga',
      'sponge',
      'levain',
      'mother dough',
      'wild yeast starter',
      'sourdough culture',
      'sourdough discard',
      'active sourdough starter',
      'ripe sourdough starter',
      'fed sourdough starter',
      'unfed sourdough starter',
      'liquid levain',
      'stiff levain',
      'firm levain',
      'liquid sourdough starter',
      'stiff sourdough starter',
      'firm sourdough starter',
      '100% hydration starter',
      '50% hydration starter',
      '60% hydration starter',
      '70% hydration starter',
      '80% hydration starter',
      '90% hydration starter',
      'whole wheat starter',
      'rye starter',
      'spelt starter',
      'einkorn starter',
      'kamut starter',
      'emmer starter',
      'farro starter',
      'barley starter',
      'oat starter',
      'buckwheat starter',
      'quinoa starter',
      'amaranth starter',
      'teff starter',
      'millet starter',
      'sorghum starter',
      'rice starter',
      'corn starter',
      'potato starter',
      'sweet potato starter',
      'pumpkin starter',
      'squash starter',
      'beet starter',
      'carrot starter',
      'parsnip starter',
      'turnip starter',
      'radish starter',
      'daikon starter',
      'ginger starter',
      'turmeric starter',
      'garlic starter',
      'onion starter',
      'shallot starter',
      'leek starter',
      'scallion starter',
      'chive starter',
      'herb starter',
      'spice starter',
      'fruit starter',
      'vegetable starter',
      'seed starter',
      'nut starter',
      'bean starter',
      'lentil starter',
      'pea starter',
      'soy starter',
      'tofu starter',
      'tempeh starter',
      'seitan starter',
      'miso starter',
      'soy sauce starter',
      'fish sauce starter',
      'oyster sauce starter',
      'hoisin sauce starter',
      'teriyaki sauce starter',
      'ponzu sauce starter',
      'worcestershire sauce starter',
      'vinegar starter',
      'kombucha starter',
      'water kefir starter',
      'milk kefir starter',
      'yogurt starter',
      'buttermilk starter', */
    ];
